version: '3'

services:
  api:
    container_name: ea-api
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_AUTHENTICATION_DATABASE=strapi
    expose:
      - 1337
    volumes:
      - ./api:/srv/app
    depends_on:
      - db
    
  db:
    container_name: ea-db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    expose:
      - 27017
    volumes:
      - ./db:/data/db
      - ./dump:/dump
    restart: always

  nginx:
    container_name: ea-nginx
    image: nginx
    # restart: always
    volumes:
      # - ./nginx/www:/usr/share/nginx/html
      # - ./nginx/default.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/default.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      # - ./letsencrypt:/etc/letsencrypt
    container_name: ea-nginx
    links:
      - api
    depends_on:
      - api
    ports:
      # - 80:80
      # - 443:443
      - 1337:1337
      # - 1338:1338