version: '3'

services:
  api:
    container_name: jme-api
    image: jme_api
    working_dir: /usr/src/api/strapi-app
    command: strapi dev
    # build: .
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
      - BASE_URL=http://localhost:8080
      # - NODE_ENV=production
    expose:
      - 1337
    volumes:
      - ./api:/usr/src/api/strapi-app
    depends_on:
      - db
    restart: always
    
  db:
    container_name: jme-db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    expose:
      - 27017
    volumes:
      - ./db:/data/db
      - ./dump:/dump
    restart: always

  nginx:
    container_name: jme-nginx
    image: nginx
    # restart: always
    volumes:
      # - ./nginx/www:/usr/share/nginx/html
      # - ./nginx/default.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/default.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      # - ./letsencrypt:/etc/letsencrypt
    container_name: jme-nginx
    links:
      - api
    depends_on:
      - api
    ports:
      # - 80:80
      # - 443:443
      - 1337:1337
      # - 1338:1338